Split struct prometheus from struct configuration
agroal/pgagroal pull request #155
Opened 2021-06-29 12:15 UTC by An-DJ

Split struct prometheus from struct configuration.

Close #153

2021-06-29 15:31 UTC, jesperpedersen requested changes

2021-06-29 15:31 UTC, jesperpedersen commented on src/include/pgagroal.h
> + * The shared memory segment for prometheus connection
"prometheus connection" -> "the Prometheus data"

2021-06-29 15:31 UTC, jesperpedersen commented on src/include/pgagroal.h
> +   char database[MAX_DATABASE_LENGTH]; /**< The database */
`struct prometheus_connection` will have a 1-to-1 relationship with `struct connection`, so this can be an empty struct to begin with

2021-06-29 15:31 UTC, jesperpedersen commented on src/include/pgagroal.h
> +   struct prometheus_connection prometheus_connections[MAX_NUMBER_OF_CONNECTIONS];  /**< The number of prometheus connections */
This needs to be a FMA field, so we only use the memory that we need.

See how `struct connection[];` is initialized after `max_connections` is known.

2021-06-29 15:31 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
> +      memset(prometheus->prometheus_connections[i].database, 0, MAX_DATABASE_LENGTH);
Remove this `memset` with a general `memset(&prometheus->prometheus_connections[i], 0, sizeof(struct prometheus_connection);`

2021-06-29 15:31 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
>  }
This needs to reset the `prometheus_connections` as well

2021-06-29 15:31 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
> +   struct prometheus* prometheus;
Keep definitions at the start of the function

2021-06-29 15:31 UTC, jesperpedersen commented on src/main.c
> +   if (pgagroal_create_shared_memory(prometheus_shmem_size, HUGEPAGE_OFF, &prometheus_shmem))
Huge page settings needs to come from the configuration

2021-06-29 15:32 UTC, jesperpedersen commented
Look at my comments, then squash and force push

2021-06-30 12:08 UTC, An-DJ commented
> Look at my comments, then squash and force push

Done

2021-06-30 15:30 UTC, jesperpedersen requested changes

2021-06-30 15:30 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
> +   struct prometheus* prometheus;
Move this to the beginning of the function

2021-06-30 15:30 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
> +
Create local variables for the size and the memory segment.

Set `p_size` and `p_shmem` to `0` and `NULL` in the beginning of the function, and only assign them if everything is successful

2021-06-30 15:30 UTC, jesperpedersen commented on src/libpgagroal/prometheus.c
> +
White space

2021-06-30 15:30 UTC, jesperpedersen commented
Just a few more

2021-07-01 01:37 UTC, An-DJ commented
> Just a few more

Done

2021-07-01 13:38 UTC, jesperpedersen commented
Thanks for your contribution !

2021-07-01 13:38 UTC, closed without merging