[#159] Add new pool metric pgagroal_query_count and `Query rate` panel
agroal/pgagroal pull request #161
Opened 2021-07-25 15:32 UTC by An-DJ

# Issue
#159 

# Task
* Add `pgagroal_query_count` which characterizes the number of queries.
* Add new panel `Query rate` in Grafana dashboard,

2021-07-26 17:32 UTC, jesperpedersen commented
This would count all client requests as a query - it would be better to just count the actual SQL queries.

See https://www.postgresql.org/docs/devel/protocol-message-formats.html for the message protocol - you will need support for the simple query and the prepared query format. You can use https://github.com/jesperpedersen/pgprtdbg for protocol debugging.

You can likely reuse code from `pipeline_transaction.c` to track message boundaries, but we need guard against this extra overhead -  maybe a `statistics` configuration variable with a default of `on`.

Only `pipeline_session.c` and `pipeline_transaction.c` needs to support this -- `pipeline_perf.c` won't support extended statistics.

2021-07-29 10:39 UTC, An-DJ commented
> This would count all client requests as a query - it would be better to just count the actual SQL queries.
> 
> See https://www.postgresql.org/docs/devel/protocol-message-formats.html for the message protocol - you will need support for the simple query and the prepared query format. You can use https://github.com/jesperpedersen/pgprtdbg for protocol debugging.
> 
> You can likely reuse code from `pipeline_transaction.c` to track message boundaries, but we need guard against this extra overhead - maybe a `statistics` configuration variable with a default of `on`.
> 
> Only `pipeline_session.c` and `pipeline_transaction.c` needs to support this -- `pipeline_perf.c` won't support extended statistics.

T

2021-08-02 13:34 UTC, An-DJ commented
@jesperpedersen I have check the message kind in `Simple Query` and `Extended Query(prepare-statement)`. 
* For the SimpleQuery, a query can be created by a `Q` message.
* For the PrepareQuery, a prepare query can be created by a `P` message which is used to parse the unsettled sql. Then a execute query can be created by a `E` message which is used to execute the settled sql.

So the query_count should be increased by 'Q' 'P' and 'E'. The newer commit includes that implementation.

2021-08-02 16:09 UTC, jesperpedersen requested changes

2021-08-02 16:09 UTC, jesperpedersen commented on src/libpgagroal/pipeline_perf.c
> +
White space

2021-08-02 16:09 UTC, jesperpedersen commented on src/libpgagroal/pipeline_session.c
> +         if (msg->kind == 'Q' || msg->kind == 'P' || msg->kind == 'E')
`P` is Parse which we shouldn't count as a query, as `B` (Bind) won't need it after 5 statements.

Lets start with `Q` and `E` in this category.

2021-08-02 16:09 UTC, jesperpedersen commented on src/libpgagroal/pipeline_transaction.c
> +         if (msg->kind == 'Q' || msg->kind == 'P' || msg->kind == 'E')
Same here.

2021-08-02 16:09 UTC, jesperpedersen commented
You are missing the reset part for the new metric

2021-08-03 05:01 UTC, An-DJ commented
> You are missing the reset part for the new metric

Done. I found that a 'P' message(parse) can be sent by `prepare` statement, and 'B','E'... messages can be sent by  `execute` statement. Maybe the parsing phase should not be considered as query. I have removed it just now.

2021-08-04 12:48 UTC, merged

2021-08-04 13:01 UTC, jesperpedersen commented
Thanks for your contribution !