[#224] Prefill when doing a `switch-to` or primary change.
agroal/pgagroal pull request #226
Opened 2022-05-04 12:14 UTC by fluca1978

Whenever the primary host is changed, by means of an explicit
`switch-to` command or by a primary failure, the connection flushing
is activated. If possible, the prefill should be also restored on the
new server.
As suggested in
<https://github.com/agroal/pgagroal/pull/225#issuecomment-1117218107>
it would be nice to check if the specified new server is the same as
the old one (failure of the primary) or a different one (`switch-to`),
and in the case they are different the prefill is forced.

2022-05-04 12:54 UTC, jesperpedersen commented
I think I like this direction a bit more.

Called the variable `primary` - and set it to `-1`, since we don't know what `server` really is. And, do the `server != (unsigned char)primary` check before the other prefill checks are done.

2022-05-04 13:06 UTC, jesperpedersen commented
I would out in an explicit `primary != -1` check as well...

2022-05-04 13:34 UTC, jesperpedersen commented
You don't need to enter the https://github.com/agroal/pgagroal/blob/master/src/libpgagroal/pool.c#L848 statement if primary isn't valid, so

```
int primary = -1;

if (pgagroal_get_primary(&primary))
{
    pgagroal_log_debug("No primary defined");
}

if (primary != -1 && server != (unsigned char)primary)
{
  // Line 848 and onwards ...

}

```

2022-05-04 13:56 UTC, jesperpedersen commented
Can you squash and force push ?

2022-05-04 14:00 UTC, jesperpedersen commented
Ah, there is still a thing.

We don't need to call prefill(false) for an old flushed primary server... which is the "if (primary != -1 && ..." check.

Otherwise it would try and prefill to `MIN_SIZE`

2022-05-05 06:02 UTC, fluca1978 commented
Just to make it clear, you don't want to prefill _at all_ if the primary is not set or the server has remained the same, right?
That makes me wondering: when it is fine to prefill to the MIN_VALUE?

2022-05-05 09:26 UTC, fluca1978 commented
Just to make it clear, you don't want to prefill _at all_ if the primary is not set or the server has remained the same, right?
That makes me wondering: when it is fine to prefill to the MIN_VALUE?

2022-05-05 11:47 UTC, jesperpedersen commented
This is only for the `flush_server` case, and yes - there should be no prefill (as `MIN_SIZE` could be > 0, and therefore cause connects to an invalid host).

There are a lot of cases where `prefill(false)` makes sense - f.ex. after validation of a connection fails or after idle timeout. This is why people need to consider `MIN_SIZE` carefully as it will tie up resources on the database cluster.

2022-05-05 13:42 UTC, fluca1978 commented
I'm not really comfortable with squashing a set of published commits, please check if it is fine now.

2022-05-05 13:49 UTC, jesperpedersen requested changes

2022-05-05 13:49 UTC, jesperpedersen commented on src/libpgagroal/pool.c
> +      prefill = server != (unsigned char)primary && primary != -1;
This needs to go into the L856 if check - and therefore you can remove  the `prefill` variable

2022-05-05 14:24 UTC, jesperpedersen commented
And, you can just do 2 levels

```
if (primary != -1 && ...
{
   // Existing code
  if (..
```

2022-05-05 14:34 UTC, fluca1978 commented
Sorry, I'm a little confused: if there is the need to prefill (number of users and limits not zero) we `fork` and issue a `pgagroal_prefill` in the child process, that then exits, while the parent process continues to memory destroy and exits too.
So what is the need to `fork` if not issuing a `pgagroal_prefill`?

2022-05-05 15:11 UTC, jesperpedersen commented
I have to check something with uncrustify - otherwise I'll merge :)

2022-05-05 15:31 UTC, jesperpedersen commented
Yeah, it could be a `static` function within `pool.c`

2022-05-06 13:26 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !

2022-05-06 13:26 UTC, closed without merging