[#215] Process title length
agroal/pgagroal pull request #284
Opened 2022-06-28 08:37 UTC by fluca1978

This is a brute force approach to set the process title with the
appropriate length.
The idea is to compute the size of the process title as it has been
requested, and set it to the computed size.

This works on Rocky Linux release 8.6 (Green Obsidian).

It could break some aggressive security-enforced environments.

See #215

2022-06-28 12:39 UTC, jesperpedersen commented
I'm getting

```
pgagroal: main  agroal.conf -a pgagroal_hba.conf -u pgagroal_users.conf
```

now instead of

```
pgagroal: main
```

using Fedora 36

2022-06-29 11:02 UTC, fluca1978 commented
Shame on me, I was focusing on having a command line *shorter* than what was required.
Commit 29a0cb53a732e1b0f1103f3317867fcab9ab5e5a should fix the problem for both commad lines shorter or longer.

I also added a separated commit 52a585a047d58039fd240a6220893567beeedaec that creates a process title in the form `user@host:port/database` like for instance `pgbench@venkman:5432/pgbench`.
I pushed it as a separated commit because I've a few doubts about it:
- it could be expensive to seek for the primary every time the process title has to be updated (this happens on every connection);
- it could the case of introducing a setting, like `update_process_title` with a few values (.e.g, `minimal`, `verbose`) to carefully decided what to state in the title

2022-06-29 17:53 UTC, jesperpedersen requested changes

2022-06-30 06:25 UTC, fluca1978 commented
Great! Commit e2b226fe991f43cc2a5596dfab08b7bffb96ef17 does everything.
I'm still wondering if it is the case to introduce a process title setting, just to avoid breaking security environments that do not allow `argv` to be overwritten brutally.
My idea would be:
- `update_process_title = strict` do not exceed `argv` initial length (i.e., as it was before this work)
- `update_process_title = minimal` do the `user/database` process title (i.e., `pgagroal_set_proc_title`)
- `update_process_tutle = verbose` do the `user@host:port/database`

Clearly, it is some amount of working for a transient information...

2022-06-30 13:02 UTC, merged

2022-06-30 13:06 UTC, jesperpedersen commented
Yeah, we could do that.

I think having `process_title` is enough with the following values

```
off - Don't touch anything
strict - <= strlen(argv)
minimal - user/database
verbose - user@host:port/database (default)
```

This is for platforms that don't have `setproctitle` system call - like Linux.

2022-06-30 13:06 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !