Improve pid file management
agroal/pgagroal pull request #300
Opened 2022-08-11 09:57 UTC by fluca1978

These commits improve a little the management of the pid file by `main` application.

2022-08-11 11:41 UTC, jesperpedersen requested changes

2022-08-11 11:41 UTC, jesperpedersen commented on src/main.c
> +      fd = open(config->pidfile, O_WRONLY | O_CREAT | O_EXCL, 0644);
Can you change this to `0640` ?

2022-08-11 11:42 UTC, jesperpedersen commented
Just squash the commits with both issues referenced.

2022-08-11 12:38 UTC, fluca1978 commented on src/main.c
> +      fd = open(config->pidfile, O_WRONLY | O_CREAT | O_EXCL, 0644);
sure

2022-08-11 12:38 UTC, fluca1978 commented
> Just squash the commits with both issues referenced.

ok, but I like more to keep commits separated...

2022-08-11 13:12 UTC, jesperpedersen commented
Could you split it into separate PRs then ? One for each issue - otherwise I can do it as part of the merge.

2022-08-11 13:22 UTC, fluca1978 commented
> Could you split it into separate PRs then ? One for each issue - otherwise I can do it as part of the merge.

I don't know how to split commits once I've rebased them and force pushed. I guess this is fine as a single PR.

My personal idea is to keep related commits into a PR/branch, and commits as short as possible to avoid "jumbo patches".

2022-08-15 16:48 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !

2022-08-15 16:48 UTC, closed without merging