feat: support all openssl errors
agroal/pgagroal pull request #350
Opened 2023-03-13 12:25 UTC by lawrence910426

The switch case does not contain all possible erros defined in [openssl manual](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html). Although ignoring `SSL_ERROR_NONE` is a clever approach and would not cause any side effects, this might be misleading to programmers from other languages.

Despite adding a new line might looks redundant, it actually enhances the readibility and maintainibility. I hope this minor change helps!

2023-03-13 12:29 UTC, lawrence910426 commented
Before submission, I have
1. `uncrustify` this PR before commit
2. Built with CMake
3. Manually tested with 1 postgresql server

Again, thanks for your time :D

2023-03-14 06:40 UTC, jesperpedersen requested changes

2023-03-14 06:40 UTC, jesperpedersen commented on src/libpgagroal/message.c
> +            case SSL_ERROR_NONE: break;
Could you move the `break;` to its own line

2023-03-14 06:40 UTC, jesperpedersen commented on src/libpgagroal/message.c
> +            case SSL_ERROR_NONE: break;
Ditto

2023-03-14 06:40 UTC, jesperpedersen commented
Add yourself to `AUTHORS`, squash and force push

2023-03-15 02:23 UTC, lawrence910426 commented
OK. I have squashed the commit. Thank you for your time :D

2023-03-15 06:54 UTC, merged

2023-03-15 06:55 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !