[#356] A better way of handling limit inconsistencies
agroal/pgagroal pull request #357
Opened 2023-03-23 12:38 UTC by fluca1978

This commit uniforms the code handling misconfigurations of limit entries into the database file.
The `max`size` is the only mandatory argument in the entry, so it drives all the others.
Now `extract_limit()` sets to zero `initial_size` and `min_size` if not specified.
When validating the limit entries, the system checks if the optional arguments have inconsistencies and, only at that point, adjusts either `min_size` or `initial_size` according to the `max_size` (that is left unchanged).
The system now clearly reports in the logs the problems, so that the user can either accept the adjustment or understand when and what the problem is.
As an example, given the following configuration:

```
$ cat /etc/pgagroal/pgagroal_databases.conf
...
pgbench pgbench 2 1  1  # ok
pgbench pgbench 5 7 1   # out of range
pgbench pgbench 7 2 9   # out of range
pgbench pgbench 5       # ok
pgbench pgbench 7 0 4   # ok
pgbench pgbench 7 0 14  # max < min
```

The logs will report:

```
WARN  configuration.c:1341 initial_size greater than max_size for limit entry 2 (/etc/pgagroal/pgagroal_databases.conf:12)
INFO  configuration.c:1344 adjusting initial_size from 7 to 5 (max_size) for limit entry 2 (/etc/pgagroal/pgagroal_databases.conf:12)
WARN  configuration.c:1332 initial_size smaller than min_size for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
INFO  configuration.c:1335 adjusting initial_size from 2 to 9 (min_size) for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
WARN  configuration.c:1341 initial_size greater than max_size for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
INFO  configuration.c:1344 adjusting initial_size from 9 to 7 (max_size) for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
WARN  configuration.c:1350 max_size smaller than min_size for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
INFO  configuration.c:1353 adjusting min_size from 9 to 7 (max_size) for limit entry 3 (/etc/pgagroal/pgagroal_databases.conf:13)
WARN  configuration.c:1350 max_size smaller than min_size for limit entry 6 (/etc/pgagroal/pgagroal_databases.conf:16)
INFO  configuration.c:1353 adjusting min_size from 14 to 7 (max_size)
for limit entry 6 (/etc/pgagroal/pgagroal_databases.conf:16)
```

Every adjusted entry is reported twice: one at WARN log level to indicate the problem, and one at INFO level to indicate the action that `pgagroal` took.

The documentation has been updated to clearly indicate that the optional values are automatically set to zero and that the system could change the settings on the fly.

Close #356

2023-03-23 23:03 UTC, 2010YOUY01 reviewed
Hi, I recently found this project cool and would like to help review :)

If changing inconsistent `initial_size` and `min_size` according to `max_size` is intended, I guess it's better done inside `pgagroal_read_limit_configuration()`? 
And `pgagroal_validate_limit_configuration()` will be used purely for validation purpose (i.e., for each `config->limits` entry check the invariant `min_size <= initial_size && initial_size <= max_size` holds) to make the implementation more robust if there are some future changes.

But I'm not sure if it's doing too much for the user, setting `MIN_SIZE` greater than `MAX_SIZE` seems a very obvious mistake. Is it better just log a fatal error and exit the program? (It's said programmers ignore warnings...which is sadly true for me)

2023-03-24 06:59 UTC, jesperpedersen requested changes

2023-03-24 06:59 UTC, jesperpedersen commented on doc/CONFIGURATION.md
> +In the case a limit entry has incoherent values, for example `initial_size` greater than `min_size`, the system will try to automatically adjust the settings on the fly, reporting messages in the log
`initial_size <= max_size && initial_size >= min_size`

2023-03-24 06:59 UTC, jesperpedersen commented on src/libpgagroal/configuration.c
> +            pgagroal_log_info("adjusting initial_size from %d to %d (min_size) for limit entry %d (%s:%d)",
adjusting -> Adjusting

2023-03-24 06:59 UTC, jesperpedersen commented on src/libpgagroal/configuration.c
> +            pgagroal_log_info("adjusting initial_size from %d to %d (max_size) for limit entry %d (%s:%d)",
adjusting -> Adjusting

2023-03-24 06:59 UTC, jesperpedersen commented on src/libpgagroal/configuration.c
> +            pgagroal_log_info("adjusting min_size from %d to %d (max_size) for limit entry %d (%s:%d)",
adjusting -> Adjusting

2023-03-24 07:01 UTC, jesperpedersen commented
I think it is ok that the system does it best to correct these issues using `WARN` and `INFO`

2023-03-24 09:17 UTC, fluca1978 commented
> Hi, I recently found this project cool and would like to help review :)
> 

Great!

> If changing inconsistent `initial_size` and `min_size` according to `max_size` is intended, I guess it's better done inside `pgagroal_read_limit_configuration()`? And `pgagroal_validate_limit_configuration()` will be used purely for validation purpose (i.e., for each `config->limits` entry check the invariant `min_size <= initial_size && initial_size <= max_size` holds) to make the implementation more robust if there are some future changes.
> 

Good point, I guess it is a matter of taste. The rationale behind my changes is that validation must return a "valid" configuration when possible, or stop the program. Moreover, leaving the adjustment phase into the read-from-file code means we will not be able to handle runtime changes (i.e., changes that do not come from a configuration file).


> But I'm not sure if it's doing too much for the user, setting `MIN_SIZE` greater than `MAX_SIZE` seems a very obvious mistake. Is it better just log a fatal error and exit the program? (It's said programmers ignore warnings...which is sadly true for me)

Again, this is a matter of taste. I tend to prefer, as you say, a program that avoids running with a bad configuration. However, there are settings that can be "guessed" and so informing the user is fine.

2023-03-24 17:45 UTC, 2010YOUY01 commented
> Good point, I guess it is a matter of taste. The rationale behind my changes is that validation must return a "valid" configuration when possible, or stop the program. Moreover, leaving the adjustment phase into the read-from-file code means we will not be able to handle runtime changes (i.e., changes that do not come from a configuration file).

That makes sense, I think again what really confused me before is three "if" clauses starting [here](https://github.com/agroal/pgagroal/pull/357/files#diff-5689399416b506f41dd77e353f880332ea3ba0a3e86816b13feac62db9d6c8a9R1330) actually did ensure the invariant `initial_size <= max_size && initial_size >= min_size`, but it is not obvious for those who first look at this piece of code, a comment/assertion can make it more understandable

2023-03-27 06:34 UTC, fluca1978 commented on doc/CONFIGURATION.md
> +In the case a limit entry has incoherent values, for example `initial_size` greater than `min_size`, the system will try to automatically adjust the settings on the fly, reporting messages in the log
ops, fixed.

2023-03-27 16:34 UTC, merged

2023-03-27 16:35 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !