Password rotation functionality without '-F'
agroal/pgagroal pull request #450
Opened 2024-05-19 08:38 UTC by ashu3103

## WORK IN PROGRESS

@jesperpedersen PTAL

### About the commit

The following commit provides a functionality to invoke a `startup` script (after reading all the configuration files)
This `startup` script generates passwords with rotation (with timeout `rotate_frontend_password_timeout`) for the frontend end user even if the frontend users file doesn't exists i.e `-F` is not provided.

It operates by creating new frontend users in the system by taking usernames from file provided in `-u` option i.e. `pgagroal_database.conf` and generating random passwords for the newly created `frontend_users`.

**Condition for startup function to work**:-
- `number_of_frontend_users` should be 0
- `rotate_frontend_password_timeout` should be non-zero

2024-05-24 20:22 UTC, ashu3103 commented on src/main.c
> +      for (int i = 0; i < config->number_of_users; i++)
Something like -->

```
if(!config){
    pgagroal_log_fatal(...)
}
```

??

2024-05-24 20:37 UTC, jesperpedersen commented on src/main.c
> +      for (int i = 0; i < config->number_of_users; i++)
https://github.com/pgmoneta/pgmoneta/blob/main/src/libpgmoneta/configuration.c#L1282

2024-05-26 04:35 UTC, ashu3103 commented
@jesperpedersen PTAL

2024-05-26 15:12 UTC, jesperpedersen requested changes

2024-05-26 15:12 UTC, jesperpedersen commented on src/main.c
> +   pgagroal_frontend_user_password_statrup(config);
This need to after the start_logging call

2024-05-26 15:12 UTC, jesperpedersen commented on src/main.c
> +   if (config->number_of_frontend_users == 0 && config->number_of_users == 0 && config->rotate_frontend_password_timeout > 0)
This check should be done in configuration.c in the validate function

2024-05-26 15:12 UTC, jesperpedersen commented on src/main.c
> +         pgagroal_log_trace("pgagroal_frontend_user_password_statrup: current password for username=%s:%s", config->frontend_users[i].username, config->frontend_users[i].password);
Just log the user name

2024-05-26 17:56 UTC, ashu3103 commented
@jesperpedersen Done

2024-05-26 19:05 UTC, jesperpedersen requested changes

2024-05-26 19:05 UTC, jesperpedersen commented on src/main.c
> +static void pgagroal_frontend_user_password_statrup(struct main_configuration* config);
Spelling -> startup

2024-05-26 19:08 UTC, ashu3103 commented on src/main.c
> +static void pgagroal_frontend_user_password_statrup(struct main_configuration* config);
Done

2024-05-26 19:27 UTC, jesperpedersen requested changes

2024-05-26 19:46 UTC, jesperpedersen commented
Rebased, and merged.

Remember, to add an issue that is referenced in the commit message.

Thanks for your contribution !

2024-05-26 19:46 UTC, closed without merging

2024-05-26 19:51 UTC, ashu3103 commented
> Rebased, and merged.
> 
> Remember, to add an issue that is referenced in the commit message.
> 

Sure, I will first raise an issue and then make PRs with respect to that issue

> Thanks for your contribution !